name: cc_default
channels:
  - conda-forge
dependencies:
  #############################################
  # System & Environment
  #############################################
  - pandas=2.2
  - seaborn=0.13
  - scikit-learn=1.6
  - imbalanced-learn=0.12
  - ipykernel=6.29
  - pip
  - pip:
    - great_tables[extra]
